const PATHS = {
  home:                      '',
  clients:                   'clients',
  projects:                  'projects',
  projectNew:                'projects/new',
  projectDetail:             'projects/:id',
  tasks:                     'tasks',
  time:                      'time',
  expenses:                  'expenses',
  quotes:                    'quotes',
  quoteNew:                  'quotes/new',
  quoteDetail:               'quotes/:id',
  settings:                  'settings',
  settingsCompany:           'settings/company',
  settingsCategories:        'settings/categories',
  settingsExpenseCategories: 'settings/expense-categories',
  settingsVatRates:          'settings/vat-rates',
  settingsProducts:          'settings/products',
} as const

export const AppRoutes = {
  paths: PATHS,
  nav: {
    home:                      `/${PATHS.home}`,
    clients:                   `/${PATHS.clients}`,
    projects:                  `/${PATHS.projects}`,
    tasks:                     `/${PATHS.tasks}`,
    time:                      `/${PATHS.time}`,
    expenses:                  `/${PATHS.expenses}`,
    quotes:                    `/${PATHS.quotes}`,
    settings:                  `/${PATHS.settings}`,
    settingsCompany:           `/${PATHS.settingsCompany}`,
    settingsCategories:        `/${PATHS.settingsCategories}`,
    settingsExpenseCategories: `/${PATHS.settingsExpenseCategories}`,
    settingsVatRates:          `/${PATHS.settingsVatRates}`,
    settingsProducts:          `/${PATHS.settingsProducts}`,
  },
} as const
